image: maven:3-openjdk-18

cache:
  paths:
    - .m2/repository

stages:
    - build
    - test
    - package
    - deploy


build_job:
    stage: build
    tags:
        - grad
    script:
        - echo "maven build started"
        - mvn compile

test_job:
    stage: test
    tags:
        - grad
    script:
        - echo "test started"
        - mvn started


package_job:
    stage: package
    tags:
        - grad
    script:
        - echo "package started"
        - mvn package


deploy_job:
    stage: deploy
    tags:
        - grad
    script:
        - echo "deploy started"
