image: maven:latest

cache:
  paths:
    - .m2/repository

stages:
    - build
    - test
    - package
    - deploy


build_job:
    stage: build
    script:
        - echo "maven build started"
        - mvn clean install
        - mvn compile
    only:
        - feature_authentication_authorization


test_job:
    stage: test
    script:
        - echo "test started"
        - mvn test
    only:
        - feature_authentication_authorization


package_job:
    stage: package
    script:
        - echo "package started"
        - mvn package
    only:
      - feature_authentication_authorization

deploy_job:
    stage: deploy
    script:
        - echo "deploy started"
    only:
      - feature_authentication_authorization